### ISSUE TITLE
Missing v2.2.3 tag and release in this repository

### ISSUE THREAD

**Issue by vitaliyf** [wbarnha/kafka-python-ng#201]
Hello,

dependabot detected https://pypi.org/project/kafka-python-ng/2.2.3/ but there is no v2.2.3 tag nor GitHub release for it.

It looks like contents of .tar.gz on pypi match 9bee9fc599c473437ebec8d90dd22ae7ed7a9bc8

Thank you for keeping this project alive!

**Comment by wbarnha** [comment]
Sorry about that. There was a mistake that occurred while doing the release! I'll re-tag.

**Comment by vitaliyf** [comment]
👍 

https://github.com/wbarnha/kafka-python-ng/releases/tag/v2.2.3
